<!--JavaScriptエラー-スローしてキャッチしよう
このtryステートメントを使用すると、コードのブロックでエラーをテストできます。

このcatchステートメントを使用すると、エラーを処理できます。

このthrowステートメントを使用すると、カスタムエラーを作成できます。
このfinallyステートメントを使用すると、結果に関係なく、tryとcatchの後にコードを実行できます。
-->
<!--エラーが発生します！
JavaScriptコードを実行すると、さまざまなエラーが発生する可能性があります。
エラーは、プログラマーによるコーディングエラー、誤った入力によるエラー、
およびその他の予期しないものである可能性があります。
この例では、意図的にエラーを生成するために、「alert」のつづりを「adddlert」と間違えました。
-->
<!DOCTYPE html>
<html>
<body>

<h2>JavaScript Error Handling</h2>

<p>How to use <b>catch</b> to display an error.</p>

<p id="demo"></p>

<script>
try {
  adddlert("Welcome guest!");
}
catch(err) {
  document.getElementById("demo").innerHTML = err.message;
}
</script>

</body>
</html>

<!--JavaScriptを試してキャッチ
このtryステートメントを使用すると、実行中にエラーをテストするコードのブロックを定義できます。

このcatchステートメントを使用すると、tryブロックでエラーが発生した場合に、実行するコードのブロックを定義できます。

JavaScriptステートメントtryとcatch ペアで提供されます。

try {
  Block of code to try
}
catch(err) {
  Block of code to handle errors
}-->